### ISSUE TITLE
Missing tag for 0.6.0

### ISSUE THREAD

**Issue by scarabeusiv** [python-caldav/caldav#48]
As per $SUBJ the tag for the latest release on pypi is missing, could you please add it?

**Comment by tobixen** [comment]
I'm on my mobile now, but I've done a best effortSent from my Huawei phone-------- Original Message --------Subject: [python-caldav/caldav] Missing tag for 0.6.0 (#48)From: Tomáš Chvátal To: python-caldav/caldav CC: Subscribed As per $SUBJ the tag for the latest release on pypi is missing, could you please add it?

**Comment by tobixen** [comment]
I really thought I fixed this a month ago, but apparently I did not manage to add the 0.6.0-tag ... bummer.  Fixing it now.

**Comment by tobixen** [comment]
Hm, the 0.6.0-tag was missing on github, but it existed on pypi.  Now I've done a mistake as the 0.6.0-tag on github contains some few bugfixes that was added after 0.6.0 was released on pypi.

Possibly I can "fix" the history and force-push through a new tag 0.6.0 and delete the old one ... but I think we should release 0.6.1 and forget about 0.6.0.

@cyrilrbt can you fix a 0.6.1-release on pypi? :-)

**Comment by cyrilrbt** [comment]
Sure, I can do that. Master's setup.py still shows 0.6.0 though, should I update it or is something else pending?

**Comment by tobixen** [comment]
Oh, nice if you can fix that, I'm only in the mobile now

**Comment by cyrilrbt** [comment]
ok, should be all good now!
